version: '1.0'
services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    ports:
      - 4080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped